# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_bankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
