# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_transactiontype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionType',
        ),
    ]
